src/diya_dnipro/news/urls.py
from django.conf.urls import url

from diya_dnipro.news.views import *


__all__ = [
    'urlpatterns',
]

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^all/$', AllView.as_view(), name='all'),
    url(r'^category/(?P<url>.+)/$', CategoryView.as_view(), name='category'),
    url(r'^search/$', SearchView.as_view(), name='search'),
    url(r'^article/(?P<pk>\d+)/$', ArticleView.as_view(), name='article'),
    url(r'^team/(?P<url>.+)/$', TeamView.as_view(), name='team'),
    url(r'^member/(?P<pk>\d+)/$', TeamMemberView.as_view(), name='member'),
    url(r'^documents/(?P<url>.+)/$', DocumentsView.as_view(), name='documents'),
    url(r'^contacts/$', ContactsView.as_view(), name='contacts'),
]

src/diya_dnipro/urls.py
from django.conf import settings
from django.conf.urls import include, url, static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.generic import TemplateView

from diya_dnipro.sitemaps import SITEMAPS


admin.site.site_header = admin.site.site_title = 'Файна адмінка'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='misc/robots.txt', content_type='text/plain'),
        name='robots'),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': SITEMAPS}, name='sitemap'),
    url(r'^', include('diya_dnipro.news.urls', namespace='news')),
    url(r'^shop/', include('diya_dnipro.shop.urls', namespace='shop'), {'beta_testing': True}),
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/diya_dnipro/misc/models.py
from fractions import Fraction

from django.core.cache import cache
from django.db import models

from diya_dnipro.misc.types import T


__all__ = [
    'SiteSetting',
]


class SiteSetting(models.Model):
    """
    Key-value storage unit.
    """
    SECTIONS = (
        (0, 'Загальне'),
        (1, 'Зовнішні посилання'),
    )
    TYPES = (
        (0, 'Текст'),
        (1, 'Ціле число'),
        (2, 'Десятковий дріб'),
        (3, 'Натуральний дріб'),
    )
    key = models.CharField(unique=True, max_length=64, verbose_name='Ключ')
    value = models.CharField(max_length=128, verbose_name='Значення')
    description = models.TextField(blank=True, verbose_name='Опис')
    section = models.PositiveSmallIntegerField(choices=SECTIONS, verbose_name='Секція')
    type = models.PositiveSmallIntegerField(choices=TYPES, verbose_name='Тип')

    class Meta:
        verbose_name = 'Налаштування'
        verbose_name_plural = 'Налаштування'

    def __str__(self) -> str:
        return '{key} = {value}'.format(key=self.key, value=self.value)

    def save(self, *args, **kwargs) -> None:
        """
        Reset cached value of SiteSetting object.
        """
        cache.delete(SiteSetting.cached_key(self.key))
        return super(SiteSetting, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs) -> dict:
        """
        Reset cached value of SiteSetting object.
        """
        cache.delete(SiteSetting.cached_key(self.key))
        return super(SiteSetting, self).delete(*args, **kwargs)

    @classmethod
    def cached_key(cls, key: str) -> str:
        """
        Form cached key for given raw key.
        """
        return 'misc:site_setting:{key}'.format(key=key)

    @classmethod
    def get_value(cls, key: str, default: T = None) -> T:
        """
        Get value for given key. If key doesn't exist, default will be return if it is present, otherwise DoesNotExist
        will be raised.
        """
        converters = {
            0: str,
            1: int,
            2: float,
            3: Fraction,
        }
        cached_key = SiteSetting.cached_key(key)
        obj = cache.get(cached_key, None)
        if obj is None:
            try:
                obj = SiteSetting.objects.get(key=key)
            except SiteSetting.DoesNotExist:
                if default is not None:
                    return default
                else:
                    raise
            else:
                cache.set(cached_key, obj)
        func = converters[obj.type]
        value = func(obj.value)
        return value

src/diya_dnipro/misc/templates/base.html
{% load static from staticfiles %}{% load compress %}{% load add_host %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=1100, initial-scale=1">
    <link rel="canonical" href="{{ request.build_absolute_uri }}">
    <meta property="og:url" content="{{ request.build_absolute_uri }}" />
    <meta property="og:site_name" content="Сайт Національного руху «ДІЯ» Дніпропетровської області" />
    <meta property="og:locale" content="uk_UA" />
    {% block open_tag_type %}
        <meta property="og:type" content="website" />
    {% endblock open_tag_type %}
    {% block open_tag_title %}
        <meta property="og:title" content="" />
    {% endblock open_tag_title %}
    {% block open_tag_description %}
        <meta property="og:description" content="" />
    {% endblock open_tag_description %}
    {% block open_tag_image %}
        <meta property="og:image" content="{% add_host %}{% static 'misc/img/open-tag-image.jpg' %}" />
        <meta property="og:image:width" content="470"/>
        <meta property="og:image:height" content="246"/>
    {% endblock open_tag_image %}
    <title>
        {% block title %}Національний рух "ДІЯ"{% endblock title %}
    </title>
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'misc/favicons/apple-touch-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'misc/favicons/apple-touch-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'misc/favicons/apple-touch-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'misc/favicons/apple-touch-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'misc/favicons/apple-touch-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'misc/favicons/apple-touch-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'misc/favicons/apple-touch-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'misc/favicons/apple-touch-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'misc/favicons/apple-touch-icon-180x180.png' %}">
    <link rel="icon" type="image/png" href="{% static 'misc/favicons/favicon-32x32.png' %}" sizes="32x32">
    <link rel="icon" type="image/png" href="{% static 'misc/favicons/android-chrome-192x192.png' %}" sizes="192x192">
    <link rel="icon" type="image/png" href="{% static 'misc/favicons/favicon-96x96.png' %}" sizes="96x96">
    <link rel="icon" type="image/png" href="{% static 'misc/favicons/favicon-16x16.png' %}" sizes="16x16">
    <link rel="manifest" href="{% static 'misc/favicons/manifest.json' %}">
    <link rel="mask-icon" href="{% static 'misc/favicons/safari-pinned-tab.svg' %}" color="#ff0000">
    <link rel="shortcut icon" href="{% static 'misc/favicons/favicon.ico' %}">
    <meta name="msapplication-TileColor" content="#00a300' %}">
    <meta name="msapplication-TileImage" content="{% static 'misc/favicons/mstile-144x144.png' %}">
    <meta name="msapplication-config" content="{% static 'misc/favicons/browserconfig.xml' %}">
    <meta name="theme-color" content="#000000' %}">
    {% compress css %}
        <link rel="stylesheet" type="text/css" href="{% static 'misc/css/reset.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'misc/css/fonts.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'misc/css/main.css' %}"/>
        {% block extra-css %}{% endblock extra-css %}
    {% endcompress %}
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
        <script src="{% static 'misc/js/html5shiv.min.js' %}"></script>
        <script src="{% static 'misc/js/respond.min.js' %}"></script>
        <link rel="stylesheet" type="text/css" href="{% static 'misc/css/ie-style.min.css' %}" />
        <script type="text/javascript">
            document.createElement('header');
            document.createElement('nav');
            document.createElement('article');
            document.createElement('footer');
            document.createElement('section');
        </script>
    <![endif]-->
    {% compress js %}
        <script type="text/javascript" src="{% static 'misc/js/jquery-1.11.3.js' %}" defer></script>
        <script type="text/javascript" src="{% static 'misc/js/main.js' %}" defer></script>
        {% block extra-js %}{% endblock extra-js %}
    {% endcompress %}
</head>
<body>
<header>
    {% if request.user.is_beta %}
        <div class="row staff">
            <div class="wrapper-in">
                Ви залогінені як випробувальник, зовнішній вигляд сайту може відрізнятись від версії для інших
                відвідувачів. Спробуйте Incognito Window для Google Chrome (Ctrl + Shift + N), Private Browsing для
                Mozilla Firefox (Ctrl + Shift + P), InPrivate для Internet Explorer (Ctrl + Shift + P), Private Browsing
                для Apple Safari (Command + Shift + N) або ж
                <a href="{% url 'admin:logout' %}?next={{ request.get_full_path }}">вилогіньтесь</a>.
            </div>
        </div>
    {% endif %}
    <div class="row above"></div>
    <div class="row middle">
        <div class="wrapper-in">
            <a href="{% url 'news:home' %}">
                <div class="logo" title="Слава Україні!"></div>
                <div class="title">
                    Національний рух "Дія" <span class="sub-title">Державницька Ініціатива Яроша</span> Дніпро
                </div>
            </a>
            <div class="icons">
                <a class="f" href="{{ facebook_url }}" title="{{ facebook_url }}"></a>
                <a class="v" href="{{ vkontakte_url }}" title="{{ vkontakte_url }}"></a>
                <a class="mail" href="mailto:{{ mail_url }}" title="{{ mail_url }}"></a>
                {% if request.user.is_beta %}
                    <a class="cart" href="#"></a>
                {% endif %}
            </div>
            <form class="search" method="get" action="{% url 'news:search' %}">
                <input type="text" placeholder="" name="q">
                <input type="submit" value="Пошук">
            </form>
        </div>
    </div>
    <div class="row below">
        <nav class="wrapper-in visible">
            <ul>
                <li class="nav-item alone">
                    <a href="{% url 'news:home' %}">Головна</a>
                </li>
                {% for elem in navigation_links %}
                    <li class="nav-item" aria-haspopup="true">
                        {{ elem.title }}
                        <ul>
                            <li><a href="{% url 'news:category' url=elem.url %}" aria-haspopup="false">Новини</a></li>
                            <li><a href="{% url 'news:team' url=elem.url %}" aria-haspopup="false">Команда</a></li>
                            <li><a href="{% url 'news:documents' url=elem.url %}" aria-haspopup="false">Документи</a></li>
                        </ul>
                    </li>
                {% endfor %}
                <li class="nav-item alone">
                    <a href="{% url 'news:contacts' %}">Контакти</a>
                </li>
            </ul>
        </nav>
    </div>
</header>
<div id="main">
    <div class="wrapper-in">
        <div class="content">{% block content %}{% endblock content %}</div>
        <div class="right-column">
            <div class="last-news">
                <div class="row">
                    <div class="news-title">Новини</div>
                    <a href="{% url 'news:all' %}">
                        <div class="all-news-link">Всі новини</div>
                    </a>
                </div>
                {% for article in last_articles %}
                    <div class="row">
                        <div class="short-article-datetime">
                            <div class="short-article-time">{{ article.created|date:"H:i" }}</div>
                            <div class="short-article-date">{{ article.created|date:"d.m.Y" }}</div>
                        </div>
                        <a href="{{ article.get_absolute_url }}" class="short-article-title"
                           title="{{ article.title }}">{{ article.title }}</a>
                    </div>
                    <hr class="row short-article-delimiter">
                {% endfor %}
            </div>
            {# <div class="notice"> #}
            {#     {% block notice %} #}
            {#         <img src="{% static 'misc/img/blokada.jpg' %}" width="353px" alt="Допомога ПС" title="Допомога ПС"> #}
            {#     {% endblock notice %} #}
            {# </div> #}
        </div>
    </div>
</div>
<footer>
    <div class="row above"></div>
    <div class="row below">
        <div class="wrapper-in">
            <div class="logo-icons">
                <a href="{% url 'news:home' %}">
                    <div class="logo" title="Героям слава!"></div>
                    <div class="title">
                        Національний рух "Дія" <span class="sub-title">Державницька Ініціатива Яроша</span> Дніпро
                    </div>
                </a>
                <div class="icons">
                    <a class="f" href="{{ facebook_url }}" title="{{ facebook_url }}"></a>
                    <a class="v" href="{{ vkontakte_url }}" title="{{ vkontakte_url }}"></a>
                    <a class="mail" href="mailto:{{ mail_url }}" title="{{ mail_url }}"></a>
                </div>
            </div>
            <div class="copyright-legal">
                <div class="copyright">
                    © 2015 - {% now "Y" %} Національний рух "ДІЯ"
                </div>
                <div class="legal">
                    Передрук та інше використання матеріалів, що розмщені на сайті, дозволяється за умови посилання
                    на {{ request.get_host }}. Інтернет-видання можуть використовувати матеріали сайту за умови
                    гіперпосилання на {{ request.get_host }}.
                </div>
            </div>
        </div>
    </div>
</footer>
</body>
</html>

src/diya_dnipro/misc/templates/error.html
{% extends "base.html" %}{% load static from staticfiles %}
{% block title %}Помилка | {{ block.super }}{% endblock title %}
{% block content %}
    <img src="{% static 'misc/img/banderivets.jpg' %}" width="727" height="634">
{% endblock content %}